### ISSUE TITLE
Versioning of processes

### ISSUE THREAD

**Issue by muffato** [sanger-tol/nf-core-pipeline#14]
This is a follow-up from discussions we had in the recent couple of months (e.g. https://github.com/sanger-tol/genomenote/pull/37 ) about how to version bespoke scripts in pipelines (Jira ticket: https://jira.sanger.ac.uk/browse/TOLIT-650 ).

For the discussion below, we can refer to the scripts and local modules under https://github.com/sanger-tol/nf-core-pipeline/tree/main/subworkflows/automate_input

First of all, we mentioned packaging those scripts in their own containers for reusability. I think we already concluded that it would have made sense had they been reusable as-is in several pipelines, but they're not, as both `tol_input.sh` and `check_samplesheet.py` need to check/retrieve the input of the pipeline (which vary between pipelines).
Since they don't have any dependencies, they can remain in `bin/` as they are now, and they'll have their history tracked together with the rest of the pipeline.

For the versioning of the scripts themselves:

- we encourage people to version each script, and print that version number. Don't need to add a `--version` option in the script: the version can be hardcoded in the `.nf` file, like in https://github.com/sanger-tol/nf-core-modules/blob/main/modules/arima/2readsbamcombiner/main.nf#L5
- otherwise, the `.nf` can default to printing the MD5 checksum of the script like in https://github.com/sanger-tol/insdcdownload/blob/dev/modules/local/masking_to_bed.nf#L29

But we would make it a requirement that there *has* to be a version.

Then, the `.nf` should also include the version of the interpreter, like [Python in `samplesheet_check.nf`](https://github.com/sanger-tol/nf-core-pipeline/blob/main/subworkflows/automate_input/modules/local/samplesheet_check.nf#L24).
With that argument, we should be printing the version of bash itself when the script is a shell script, e.g. [`tol_input.sh`](https://github.com/sanger-tol/nf-core-pipeline/blob/main/subworkflows/automate_input/modules/local/input_tol.nf#L23-L28).
But, when you think about it, almost _all_ Nextflow modules define the command in the `script:` section of the `.nf`, meaning that there is _always_ a Shell script involved (even for samtools !). I wouldn't want to print the bash version for the latter. Does it still make sense to print the bash version when the external script is a shell script ?

Finally, we could _recommend_ people to print the version of major components / dependencies of the script, the same way our arima module prints the version of samtools too: https://github.com/sanger-tol/nf-core-modules/blob/main/modules/arima/2readsbamcombiner/main.nf#L32-L33
This, applied to shell scripts, would mean identifying the main commands, etc, run by it, and printing their version. This is not trivial because many containers ship [busybox](https://busybox.net/downloads/BusyBox.html) to provide `ls`, `cut`, `head`, etc. So we'd end up with something like https://github.com/sanger-tol/nf-core-pipeline/compare/main...process_versioning#diff-22432af269a8d580704bd747b70ba6fe219bd9800c0b5707a9f3e76e83a7c6d9R30
Coming back to [`tol_input.sh`](https://github.com/sanger-tol/nf-core-pipeline/blob/main/subworkflows/automate_input/bin/tol_input.sh#L26), I'm not sure it's worth reporting the version of [awk](https://github.com/sanger-tol/nf-core-pipeline/blob/main/subworkflows/automate_input/modules/local/input_tol.nf#L27) itself, because it's such a minor and straightforward thing to do.

**Or**, I'm looking at it from the wrong angle and making it unnecessary complex. In the end, the script runs within a container which includes all of that (`python`, `bash`, `awk`, `cut`, `ls`, etc), and what's really important to report is the version of the container only since all the other versions (except the script itself) can be found inside the container ?

**Comment by priyanka-surana** [comment]
I think leaving it out makes most sense.
With container version, if we use ubuntu or something, it doesn't make sense in context of the script.
As you mentioned, we change scripts between pipeline, so md5sum is just a record, won't mean more than that.

**Comment by muffato** [comment]
I have updated the pull-request #13 and the [FAQ](https://github.com/sanger-tol/nf-core-pipeline/wiki/FAQ) following the guidelines we agreed yesterday
