### ISSUE TITLE
Wiki pages: Set up pipeline

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/nf-core-pipeline#6]
JIRA: https://jira.sanger.ac.uk/browse/TOLIT-559

To complete this issue write pages to:
1. overview setup
2. set up pipeline using `nf-core/tools`
3. set up dev and main branch protection
5. integrate `automate_input` subworkflow from `sanger-tol/nf-core-pipeline`
6. update config files
    – `nextflow.config` 
    – `conf/base.config` 
    – `conf/modules.config` 
    – `conf/test.config` and `conf/test_full.config`

**Comment by priyanka-surana** [comment]
2. set up pipeline using nf-core/tools: https://github.com/sanger-tol/nf-core-pipeline/wiki/Setting-up-a-pipeline

**Comment by priyanka-surana** [comment]
@muffato @gq1 Since there won't be an official PR for this issue. I will post the new page links here. Feel free to review either individually or later as a whole. Looking forward to your comments.

**Comment by priyanka-surana** [comment]
2. set up pipeline using nf-core/tools: https://github.com/sanger-tol/nf-core-pipeline/wiki/Setting-up-a-pipeline

**Comment by priyanka-surana** [comment]
3. set up dev and main branch protection: https://github.com/sanger-tol/nf-core-pipeline/wiki/Feature-and-development-branches

**Comment by muffato** [comment]
(for clarity, there isn't "an official PR" because the changes occur in the wiki, which doesn't support pull-requests. PRs are only on the main code repository)

**Comment by priyanka-surana** [comment]
Done 👍
